#!/bin/bash
arch=$(uname -a)
vcpu=$(cat /proc/cpuinfo|grep 'cpu cores'|uniq|cut -c12-13)
pcpu=$(cat /proc/cpuinfo|grep 'physical id'|sort|uniq|wc -l)
memusg_mg=$(free |grep Mem |awk '{print $3/1024 - $3/1024%1}')
memusg_mgtotal=$(free |grep Mem |awk '{print $2/1024 - $2/1024%1}')
memproc=$(free |grep Mem |awk '{print $3/$2 * 100}'|cut -c1-3)
memend=$(echo $memusg_mg / $memusg_mgtotal MB \($memproc % \) )
diskusg=$(df -hm |grep LVMGroup|awk '{print $3}'|tr -d "%a-zA-Z"|
	tr -s "\n" " "|awk '{print (($1+$2$+3$+4$+5$+6) / 1024)}'|cut -c1-3)
diskusg_proc=$( echo $diskusg $diskusg_total |awk '{print $1 / ($2 / 100)}')
diskusgend=$(echo $diskusg / $diskusg_total GB \( $diskusg_proc % \)) 
cpuusg=$(top -b -n1 |grep "Cpu(s)" | awk '{print $a + $4}')
lastboot=$(who -b|cut -c23-38)
lvm=$(if lsblk |grep lvm > /dev/null; then echo "yes";fi)
contcp=$(ss -an|grep ESTAB |wc -l) 
ulog=$(who|wc -l)
 #ulog=$(w|grep "load average"|awk '{print $4}')
ip=$(hostname -I)
mask=$(ip -c a|grep ether|awk '{print $2}')
sudo=$(cat /var/log/sudo/sudo.log|grep -c COMMAND )

wall "#Architecture: $arch
#CPU physical: $pcpu
#vCPU: $vcpu
#Memory Usage: $memend
#Disk Usage: $diskusgend 
#CPU load: $cpuusg
#Last boot: $lastboot
#LVM use: $lvm
#Connexions TCP: $contcp ESTABLISHED
#User log: $ulog
#Network: IP $ip $mask
#Sudo: $sudo cmd "
